/**
 * Centralized Social Hub platform configuration.
 * Static UI metadata only — no secrets, tokens, or API keys.
 */

export const SOCIAL_PROVIDERS = [
  {
    id: "instagram",
    name: "Instagram",
    description: "Connect your Instagram account for Reels and feed posts.",
    icon: "Instagram",
    color: "#e1306c",
    providerId: "instagram",
    configured: false,
    available: false,
    oauthImplemented: true,
    capabilities: {
      connect: true,
      publish: true,
      schedule: true,
      media: true,
      video: true,
      image: true,
      text: true,
      analytics: true,
    },
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "Connect your TikTok account for short-form promo videos.",
    icon: "Music2",
    color: "#ff2d55",
    providerId: "tiktok",
    configured: false,
    available: false,
    oauthImplemented: true,
    capabilities: {
      connect: true,
      publish: true,
      schedule: true,
      media: true,
      video: true,
      image: false,
      text: true,
      analytics: true,
    },
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "Connect your YouTube channel for Shorts and video posts.",
    icon: "Youtube",
    color: "#ff0000",
    providerId: "youtube",
    configured: false,
    available: false,
    oauthImplemented: true,
    capabilities: {
      connect: true,
      publish: true,
      schedule: true,
      media: true,
      video: true,
      image: false,
      text: true,
      analytics: true,
    },
  },
  {
    id: "facebook",
    name: "Facebook Page",
    description: "Connect a Facebook Page you manage for posts and your public profile links.",
    icon: "Facebook",
    color: "#1877f2",
    providerId: "facebook",
    configured: false,
    available: false,
    oauthImplemented: true,
    capabilities: {
      connect: true,
      publish: true,
      schedule: true,
      media: true,
      video: true,
      image: true,
      text: true,
      analytics: false,
    },
  },
  {
    id: "x",
    name: "X",
    description: "Connect your X account (formerly Twitter) for posts and profile links.",
    icon: "XBrand",
    color: "#e7e9ea",
    providerId: "x",
    configured: false,
    available: false,
    oauthImplemented: true,
    capabilities: {
      connect: true,
      publish: true,
      schedule: true,
      media: true,
      video: false,
      image: true,
      text: true,
      analytics: false,
    },
  },
];

export const getSocialProviderConfig = (id) =>
  SOCIAL_PROVIDERS.find((p) => p.id === id) || null;
